workflow:
  rules:
    # switch from branch pipelines to merge request pipelines when a merge request is created.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
      when: never
    # - A merge request pipeline, start the pipeline. For example, a merge request pipeline can be triggered by a push to a branch with an associated open merge request.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # - A branch pipeline, but a merge request is open for that branch, do not run the branch pipeline. For example, a branch pipeline can be triggered by a change to a branch, an API call, a scheduled pipeline, and so on.
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    # - A branch pipeline, but there is no merge request open for the branch, run the branch pipeline.
    - if: $CI_COMMIT_BRANCH

image: python:3.12

stages:
  - build
  - test

before_script:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  # - mypy --install-types

pytest:
  stage: test
  script:
    - pytest tests

mypy:
  stage: test
  script:
    - mypy --install-types --non-interactive --check-untyped-defs ./

black:
  stage: test
  script:
    - black --diff --check ./

isort:
  stage: test
  script:
    - isort --check-only ./

flake8:
  stage: test
  script:
    - flake8 --config=.flake8 ./
